[package]
name = "se-bruteforcer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# selenium-rs = "0.1.2"
tokio = "1.20.1"
thirtyfour = "0.31.0"
dialoguer = "0.10.2"
anyhow = "1.0.62"